### PR TITLE
Feature/entk integration

### PR DESCRIPTION
**Pull request by vivek-bala**

### CODE REVIEW

**Comment by vivek-bala** [comment]
This is an old branch which lets users use analytics with EnTK. A few commits were left out in a previous merge. Current feature/entk-integration is synced with devel.

**Comment by andre-merzky** [comment]
The only diff in this PR is the addition of Jumana's wrangler?  I am happy to merge that of course, but wanted to check with you if this was the intent for this PR?

**Comment by vivek-bala** [comment]
I see. You're right. I think the missing commit did not get merged with master. Specifically, that commit should have included https://github.com/radical-cybertools/radical.analytics/blob/devel/src/radical/analytics/session.py#L97-L98.

**Comment by andre-merzky** [comment]
Ah, I see - I brought devel and master in sync now, and pushed a new release out (`0.50.1`), which contains that commit.  I'll merge this PR into devel now, so that the wrangler is available there, too.

Thanks!

**Pull request merged**
