### PR TITLE
Feature/uid filter

### PR DESCRIPTION
**Pull request by andre-merzky**
allow to filter session by uid regex matching

### CODE REVIEW

**Comment by andre-merzky** [comment]
@okilic1 , @mturilli - this should actually be ready for testing.  You can now specify a regular expression (or type `re.Pattern`) as uid filter on a session.

**Comment by andre-merzky** [comment]
You can test this for example with:

```py
    pat = re.compile('^.*0$')
    s2 = session.filter(uid=pat)

    for e in s2.get():
        print('===', e.uid)
```

which should result in a session which has only entities whose uids end on `0`:

```sh
$ ./examples/00_session_describe_rp.py ~/j/rp/rp.session.thinkie.merzky.019622.0014/
1696281856.321 : radical.analytics    : 174194 : 139899907416128 : INFO     : radical.analytics    version: 1.35.0-v1.34.0-6-g430bb2d@feature-uid_filter
using cache for rp.session.thinkie.merzky.019622.0014
=== cmgr.0000
=== stager.0000
=== pmgr_launching.0000
=== pmgr.0000
=== pilot.0000
=== tmgr_staging_input.0000
=== tmgr_scheduling.0000
=== tmgr_staging_output.0000
=== tmgr.0000
=== task.000000
=== task.000010
=== task.000020
=== task.000030
=== task.000040
=== task.000050
=== task.000060
=== task.000070
=== task.000080
=== task.000090
=== task.000100
=== task.000110
=== task.000120
```

**Comment by andre-merzky** [comment]
I improved this a bit to:

```py
    pat1 = 'pilot.0001'
    pat2 = re.compile(r'^task\..*0$')
    s2 = session.filter(uid=[pat1, pat2])

    for e in s2.get():
        print('===', e.uid)
```

which should be what we need I think:

```sh
$ ./examples/00_session_describe_rp.py ~/j/rp/rp.session.thinkie.merzky.019622.0014/
=== pilot.0001
=== task.000000
=== task.000010
=== task.000020
=== task.000030
=== task.000040
=== task.000050
=== task.000060
=== task.000070
=== task.000080
=== task.000090
=== task.000100
=== task.000110
=== task.000120
```

**Review by mturilli — APPROVED** [review]
LGTM! Thanks.

**Pull request merged**
