### PR TITLE
Enables arbitrary unit durations for duration method

### PR DESCRIPTION
**Pull request by mturilli**
This enable defining arbitrary units durations for get_consumed_resources. This allows to correctly plot resource utilization when some event timestamps are not available. It is backward compatible with the previous API. Depends on https://github.com/radical-cybertools/radical.pilot/pull/2205

### CODE REVIEW

**Review by andre-merzky — APPROVED** [review]
Nice :-)

**Comment by mturilli** [comment]
Thanks! Note that 991 triggers E1121 because, I guess, it installs the master version of rp.utils. Any idea how I would tell Travis to use a specific branch for rp.utils?

**Comment by andre-merzky** [comment]
> Note that 991 triggers E1121 because, I guess, it installs the master version of rp.utils. Any idea how I would tell Travis to use a specific branch for rp.utils?

@iparask : any suggestion?

**Comment by iparask** [comment]
In `travis.yml`, we can add something like pip install `https://github.com/radical-cybertools/radical.utils`.

**Pull request merged**
